# These are the explicit defaults, modify them as needed

printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
arrowParens: always
rangeStart: 0
# rangeEnd: Infinity
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: auto
embeddedLanguageFormatting: auto
singleAttributePerLine: false
